
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    # "--no-tree-shake-icons" you can add this flag if you want to disable tree shaking for icons
    sh "flutter build apk --release --flavor production --target lib/main_production.dart" 
    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        groups: "general-testers",
        release_notes: "Final touch for fastlane with GitHub Actions."
  )
  end
end